# 必需配置
timezone: Asia/Tokyo
static: true
build: false

# 可选优化（用于可视化编辑）
cloudcannon:
  editable_elements: true
  preview:
    css:
      - /css/styles.css
  options:
    inputs:
      hero-title:
        type: text
        label: ヒーローセクションタイトル
      hero-subtitle:
        type: text
        label: ヒーローセクションサブタイトル
