# _config.yml
timezone: Asia/Tokyo
static: true
build: false

# CloudCannon 高级配置
cloudcannon:
  editable_elements: true
  preview:
    css: /css/styles.css
  collections:
    pages:
      output: true
  data:
    inputs:
      hero_title:  # 与HTML中的name对应
        type: text
        label: "ヒーローセクションタイトル"
        description: "メインヘッドラインを編集"
      hero_subtitle:
        type: text
        label: "ヒーローセクションサブタイトル"
