# CloudCannon 配置
cloudcannon:
  editable_elements: true
  data:
    inputs:
      # 文本类
      logo:
        type: html
        label: "ロゴ"
      main_title:
        type: text
        label: "メインタイトル"
      subtitle:
        type: text
        label: "サブタイトル"
      cta_button:
        type: html
        label: "ボタンテキスト"

      # HTML内容块
      about_description:
        type: html
        label: "カフェ概要"
      business_info:
        type: html
        label: "営業情報"

      # 图片类
      owner_photo:
        type: image
        path: "/images/"
        label: "オーナー写真"
      
      # 特征区块
      feature_book:
        type: html
        label: "書籍特徴"
      feature_coffee:
        type: html
        label: "コーヒー特徴"
      feature_music:
        type: html
        label: "音楽ライブ特徴"

      # 画廊
      gallery:
        type: array
        item_type: image
        path: "/images/gallery/"
        label: "ギャラリー画像"
        item_config:
          alt:
            type: text
            label: "画像説明"
