timezone: Asia/Tokyo
static: false
build: true
cloudcannon:
  editable_elements: true
  preview:
    css: /css/styles.css
  collections:
    pages:
      output: true
  data:
    inputs:
      hero_title:
        type: text
        label: ヒーローセクションタイトル
        description: メインヘッドラインを編集
      hero_subtitle:
        type: text
        label: ヒーローセクションサブタイトル
