backend:
  name: github
  repo: player-bit/cafe-website
  branch: main

media_folder: "images"       # 上传图片后保存的位置
public_folder: "/images"

collections:
  - name: "books"
    label: "今日の一冊"
    folder: "books"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "紹介文", name: "body", widget: "markdown" }
      - { label: "表紙画像", name: "cover", widget: "image" }
