backend:
  name: git-gateway
  branch: main

# 添加以下配置
publish_mode: editorial_workflow
show_preview_links: true

# 禁用自动初始化
cms_manual_init: true

collections:
  - name: "blog"
    label: "文章"
    folder: "content/blog"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
