backend:
  name: git-gateway
  branch: main

# 媒体配置 - 必须添加
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# 媒体库配置 - 强烈推荐
media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

collections:
  - name: "blog"
    label: "文章"
    folder: "content/blog"
    create: true
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "封面图片", name: "image", widget: "image" }
      - { label: "内容", name: "body", widget: "markdown" }
